#!/usr/bin/env node
var cmd = require('commander');
var convert = require('./convert');

cmd
    .version('0.0.1')
    .usage('<exportFile Path> or <exportFile Path> timezone=off')
    .parse(process.argv);

if (!cmd.args.length || cmd.args.length > 2) {
    cmd.help();
    process.exit();
}

convert.apply(null, cmd.args);
