#!/usr/bin/env node
var cmd = require('commander');
var convert = require('./convert');

const pkg = require('./package.json');

cmd
    .version(pkg.version)
    .usage('<exportFile Path> or <exportFile Path> timezone=off')
    .option('-e, --export [path]', 'Export File.')
    .option('-t, --timezone', 'timezone fix')
    .option('-u, --useCategoryHacks', 'use category hacks')
    .parse(process.argv);

if (!cmd.args.length || cmd.args.length > 4 || !cmd.export) {
    cmd.help();
    process.exit();
}

convert(cmd.export, cmd.timezone || 'off', cmd.useCategoryHacks || false);
